### ISSUE TITLE
[PE-D][Tester E] Date error message is not descriptive

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T09-1/tp#236]
![image.png](https://raw.githubusercontent.com/zbz-lvlv/ped/main/files/b063a093-221a-4013-ba6a-8b5a3808a033.png)

The error message given for an invalid date is the same as the error message given for other errors. It is not immediately clear that the mistake is made in the wrong date format.

30/02/2022 doesn't exist.

Remedy: Tell the user the specific mistake made

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: zbz-lvlv/ped#5

**Comment by ElginL** [comment]
Good spot.

We can fix this in `v1.4`

![image](https://user-images.githubusercontent.com/88147891/198887651-55c4f168-6637-4951-b58f-0adbbd8badec.png)
