### ISSUE TITLE
[PE-D][Tester C] Cannot add client with same name but different details.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-T09-1/tp#251]
![image.png](https://raw.githubusercontent.com/doimoiboi/ped/main/files/b01119e8-be48-4fb9-89f7-45ec8a0e341d.png)

When adding a new client, it seems that if it has the same name as an existing client, it is considered a duplicate despite having different details.
Perhaps allow this since different clients might share the same name but have different addresses or phone numbers.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: doimoiboi/ped#3

**Comment by ElginL** [comment]
This is not a bug. 

Our thought process: If we allow 2 clients have the same name, but different details in different fields, then how are we supposed to know who is who?

For instance, if we have two `john` in the client list, both having different phone number, when we want to contact the `john` that we want, how do we know which one is the one we are looking for?
